// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolSource } from "./AccountPoolSource";
import type { AccountPoolTokenHealth } from "./AccountPoolTokenHealth";
import type { AccountPoolUsageHealth } from "./AccountPoolUsageHealth";

export type AccountPoolAccount = { alias: string, source: AccountPoolSource, email: string | null, planType: string | null, tokenHealth: AccountPoolTokenHealth, usageHealth: AccountPoolUsageHealth, isCurrent: boolean, };
